activeProfileName: default
server:
    port: 0 #random port
    servlet:
        context-path: /bank-account-service
spring:
    application:
        name: ms-bank-account
    datasource:
        url: jdbc:sqlite:bank-account-database.db
        driver-class-name: org.sqlite.JDBC
        username: admin
        password: admin
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            database-platform: org.hibernate.community.dialect.SQLiteDialect

info:
    app:
        name: MS BANK ACCOUNT
        description: API para gestión de cuentas bancarias
        version: v1

# http://localhost:{port}/swagger-ui/index.html
springdoc:
    api-docs:
        title: "MS BANK ACCOUNT"
    swagger-ui:
        title: "Documentación - API de Clientes"
    # swagger-ui custom path
    #swagger-ui.path: /swagger-ui.html
    # Disabling the swagger-ui
    #swagger-ui.enabled: true

eureka:
    client:
        serviceUrl:
            #podriamos tener multiples instancias de eureka, o quizas un proveedor distinto
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
        #indicates that this ms is a eureka client
        register-with-eureka: true
        #for notice to eureka if this ms is available, needs actuator
        healthcheck:
            enabled: true
        fetch-registry: true
    instance:
        prefer-ip-address: true

#expose all actuator endpoints
#by default actuator expose /health and /info only
# /ms-customer/actuator/health , /ms-customer/actuator/info
management:
    endpoints:
        web:
            exposure:
                include: '*'
logging:
    #config: classpath:log4j2-spring.xml
    level:
        com.bank: DEBUG
        #org.springframework: INFO
        #root: INFO